### ISSUE TITLE
Failed to run healthcheck for "rustaceanvim" plugin.

### ISSUE THREAD

**Issue by h0pes** [mrcjkb/rustaceanvim#103]
Output of `healthcheck`:

```bash
rustaceanvim: require("rustaceanvim.health").check()

- ERROR Failed to run healthcheck for "rustaceanvim" plugin. Exception:
  function health#check, line 25
  Vim(eval):E5108: Error executing lua [string "luaeval()"]:1: loop or previous error loading module 'rustaceanvim.health'
  stack traceback:
  [C]: in function 'require'
  [string "luaeval()"]:1: in main chunk

```
I don't know if this is a problem with my nvim (V0.9.4) configuration or it's a plugin issue. I have just updated all my plugins and the NvChad framework I use and it's not working anymore.
I have not change the `rustaceanvim` configuration in a while...
rust-analyzer LSP does not attach anymore to .rs files

**Comment by mrcjkb** [comment]
Hey :wave: 

Thanks for reporting. That's strange. It works for me.
Could you please post your `vim.g.rustaceanvim` config if you have one?

**Comment by h0pes** [comment]
Thanks for the prompt reply.
Yes, sure.
Here it is (as I said I'm using NvChad framework and Lazy vim):

```bash
  -- rustaceanvim: https://github.com/mrcjkb/rustaceanvim
  -- new plugin which replaces rust-tools
  {
    "mrcjkb/rustaceanvim",
    version = "^3", -- Recommended
    ft = { "rust" },
    init = function()
      require("core.utils").load_mappings "rustaceanvim"
      vim.g.rustaceanvim = {
        -- Plugin configuration
        tools = {
          autoSetHints = true,
          inlay_hints = {
            show_parameter_hints = true,
            parameter_hints_prefix = "<- ",
            other_hints_prefix = "=> ",
          },
        },
        server = {
          on_attach = function(client, bufnr)
            require("illuminate").on_attach(client)
            local bufopts = {
              noremap = true,
              silent = true,
              buffer = bufnr,
            }
            vim.keymap.set("n", "<leader><leader>rr", "<Cmd>RustLsp runnables<CR>", bufopts)
            vim.keymap.set("n", "K", "<Cmd>RustLsp hover actions<CR>", bufopts)
          end,
          settings = {
            -- rust-analyzer language server configuration
            ["rust-analyzer"] = {
              assist = {
                importEnforceGranularity = true,
                importPrefix = "create",
              },
              cargo = { allFeatures = true },
              checkOnSave = {
                -- default: `cargo check` but `clippy` can be used too.
                command = "cargo check",
                allFeatures = true,
              },
              inlayHints = {
                lifetimeElisionHints = {
                  enable = true,
                  useParameterNames = true,
                },
              },
            },
          },
        },
      }
    end,
  },

```

**Comment by mrcjkb** [comment]
I just tried out your config and couldn't reproduce it :disappointed: 

One thing looks strange to me:

```lua
require("core.utils").load_mappings "rustaceanvim"
```

I had to leave it out of my test, because I don't have a `core.utils` module.

Is this a LazyVim thing? Or is it a function in your personal config?
I suppose it is supposed to load some keymaps?

One thing you can try is to follow the [troubleshooting section](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#troubleshooting).
I provide a minimal config file that you can add your settings and the plugins you use to one-by-one, until you can reproduce the error.

It uses plain Neovim though - I'm afraid I don't have the capacity to support all the distros out there.

I don't think it's caused by another plugin though.
The error, `loop or previous error loading module` usually means there's a cyclic dependency between modules that couldn't be evaluated at runtime.

**Comment by mrcjkb** [comment]
I've just pushed a change that may or may not help prevent that error.

**Comment by h0pes** [comment]
Thank you very much for your help.
Indeed the line `require("core.utils").load_mappings "rustaceanvim"` is to load some custom mappings accordingly to NvChad docs (see [here](https://nvchad.com/docs/config/mappings) at the end of page).
I tried commenting out that line before pulling your change, but nothing changed. 
Also after upgrading the plugin to the latest commit, the issue is still there (same error as before, just ln numbers changed).
This is definitely something with my config I think.
The fact that LSP does not attach when opening a Rust file it's somehow strange, in fact if I `:Lazy load rustaceanvim` after having opened any other filetype and I run `:checkhealth rustaceanvim` I get the following interesting output:
```bash
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 1.74.1 (a28077b 2023-12-04)
- OK Cargo: found cargo 1.74.1 (ecb9851af 2023-10-18)
- OK rustc: found rustc 1.74.1 (a28077b28 2023-12-04)
- OK lldb: found lldb version 16.0.6

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- ERROR lspconfig.rust_analyzer has been setup. This will likely lead to conflicts with the rustaceanvim LSP client.
```
I wonder that error where comes from, as I haven't modified my `lspconfig.lua` and I don't even have the LSP server installed via `Mason`, as I have always relied on the `rust-analyzer` version from `rustup` which is indeed installed and updated on my system.

**Comment by h0pes** [comment]
I made a silly test, adding the `cmd` setting to the `server` configuration section of the plugin, specifying the path to `rust-analyzer`, like:
`cmd = { "/home/marco/.cargo/bin/rust-analyzer" },`
and it seems to work fine again.
I wonder if this makes sense. I had to modify my `$PATH` recently to manage some custom binaries and now I have those dirs before the `.cargo/bin` one. 
Dunno if that could be the reason...

**Comment by mrcjkb** [comment]
That makes sense. The LSP client won't auto attach if neovim can't find the executable specified in `server.cmd`.

You can try with `:lua =vim.fn.executable('rust-analyzer') `. If it doesn't evaluate to `1`, it means it's not on your `PATH`.

The 

```
- ERROR lspconfig.rust_analyzer has been setup. 
```

means that something (likely a plugin, usually mason-lspconfig) is causing it to be setup.
See also [this discussion](https://github.com/mrcjkb/rustaceanvim/discussions/94).

If you're using mason-lspconfig, the solution will probably be something similar.

**Comment by h0pes** [comment]
Sorry for the late reply.
Indeed `:lua =vim.fn.executable('rust-analyzer')` evaluates to `1`.
I do not have `rust_analyzer` LSP server installed via Mason and I do not use `mason-lspconfig` as I know it can cause some conflicts.
This is what happens: if I open a `Rust` file with other LSP servers configured to work with `filetypes = "rust"` disabled in my `custom/config/lspconfig.lua`, everything works fine. I see just `rust-analyzer` as the one LSP server attached.
If I try to enable other LSP server to work with `rust filetypes`, like I have `tailwindcss` and `emmet_ls`, then I got all two or three of them attached (this is correct), but `:checkhealth rustaceanvim` reports the error `ERROR lspconfig.rust_analyzer has been setup.`
I attach some screens for reference. I didn't noticed that before and I don-t know what to do (I also added the suggested lines to `return` if `lsp == 'rust_analyzer'`.
I don't know how to track where `rust_analyzer` is triggered...

![2023-12-22_12-16_rustaceanvim_ko](https://github.com/mrcjkb/rustaceanvim/assets/25418553/3f327d10-c4a4-421a-a53f-f8b031e7cdb7)
![2023-12-22_12-20_LspInfo](https://github.com/mrcjkb/rustaceanvim/assets/25418553/1cf7f8d4-b3d5-45b7-8a54-f37121841e20)
![2023-12-22_12-16_rustaceanvim_ok](https://github.com/mrcjkb/rustaceanvim/assets/25418553/ef88d76d-f721-4a44-b836-1d1cc7554d2c)

A [gist](https://gist.github.com/h0pes/89b76bc8b9ca7741a4b4efe34e1764e8) with my lspconfig.

**Comment by mrcjkb** [comment]
Ah, this is a bug in the health check. It just checks if an lspconfig autocommand for rust filetypes has been setup, assuming it's the rust_analyzer config.

You can ignore the error for now. As long as there's no rust_analyzer client created by lspconfig attached to your buffer, everything is fine.

**Comment by mrcjkb** [comment]
Should be fixed with version 3.10.5: https://github.com/mrcjkb/rustaceanvim/commit/259f881c6bea51338e5ff72fc3a366008013c8c6

**Comment by h0pes** [comment]
Thanks, I confirm that `healthcheck` does not produce that error anymore.
