### ISSUE TITLE
[Windows] completions not working.

### ISSUE THREAD

**Issue by Alan-Manning** [mrcjkb/rustaceanvim#274]
### Neovim version (nvim -v)

v0.9.4

### Operating system/version

OS Name	Microsoft Windows 11 Pro N Version	10.0.22631 Build 22631

### Output of :checkhealth rustaceanvim

```console
rustaceanvim: require("rustaceanvim.health").check()

Checking for Lua dependencies ~
- OK [mfussenegger/nvim-dap](https://github.com/mfussenegger/nvim-dap) installed.

Checking external dependencies ~
- OK rust-analyzer: found rust-analyzer 0.3.1860-standalone (5346002d0 2024-02-25)
- OK Cargo: found 
- OK rustc: found 
- OK lldb: found 

Checking config ~
- OK No errors found in config.

Checking for conflicting plugins ~
- OK No conflicting plugins detected.

Checking for tree-sitter parser ~
- OK tree-sitter parser for Rust detected.
```

### How to reproduce the issue

```console
cd to the root of the rust project.
nvim
opens - navigate to a file
try to get some completions working while typing. All i see is text and snippets in completions menu.
restart lsp nothing still.
```

### Expected behaviour

The completions should be managed by nvim cmp however they are not loading the lsp source in the completions list.

### Actual behaviour

all i get is the text and snippets completions sources. not the lsp completion sources that should be there ( and infact  the ones i do get when i used to set up rust analyzer myself with lspconfig and the rusttools plugin).

### The minimal config used to reproduce this issue.

rustaceanvim.lua

```lua
return {
	"mrcjkb/rustaceanvim",
	version = "^4", -- Recommended
	ft = { "rust" },
	config = function()
		-- local mason_registry = require("mason-registry")
		--
		-- local codelldb = mason_registry.get_package("codelldb")
		-- local extension_path = codelldb:get_install_path() .. "/extension/"
		-- local codelldb_path = extension_path .. "adapter/codelldb"
		-- local liblldb_path = extension_path .. "lldb/lib/liblldb.dylib"

		vim.g.rustaceanvim = {
			-- Plugin configuration
			-- LSP configuration
			server = {
				tools = {
          executor = "toggleterm",
					hover_actions = {
						auto_focus = true,
					},
				},
				capabilities = require("cmp_nvim_lsp").default_capabilities(),
				on_attach = function(_, bufnr)
					-- you can also put keymaps in here

					local opts = { buffer = bufnr }

					-- Formatting here becuase nonels does not get loaded for formatring rust.
					vim.keymap.set({ "n", "v" }, "<leader>mp", function()
						vim.lsp.buf.format({ timeout_ms = 10000 })
					end, { desc = "Format File" })
					-- Code Actions
					opts.desc = "See available code actions"
					vim.keymap.set("n", "<leader>ca", function()
						vim.cmd.RustLsp("codeAction")
					end, opts)

					-- Show Documentation for what is under cursor
					opts.desc = "Show documentation under cursor"
					vim.keymap.set("n", "<leader>k", function()
						vim.cmd.RustLsp({ "hover", "actions" })
					end, opts)

					-- Explain Error
					opts.desc = "Explain Error"
					vim.keymap.set("n", "<leader>ex", function()
						vim.cmd.RustLsp("explainError")
					end, opts)

					-- Render Diagnostic
					opts.desc = "Render diagnostics"
					vim.keymap.set("n", "<leader>d", function()
						vim.cmd.RustLsp("renderDiagnostic")
					end, opts)

					-- SECTION BELOW IS COPIED FROM lspconfig.lua

					-- show definition, references
					opts.desc = "Show LSP references"
					vim.keymap.set("n", "gR", "<cmd>Telescope lsp_references<CR>", opts)

					-- go to declaration
					opts.desc = "Go to declaration"
					vim.keymap.set("n", "gd", vim.lsp.buf.declaration, opts)

					-- show lsp definitions
					opts.desc = "Show LSP definitions"
					vim.keymap.set("n", "gD", "<cmd>Telescope lsp_definitions<CR>", opts)

					-- show lsp implementations
					-- opts.desc = "Show LSP implementations"
					-- vim.keymap.set("n", "gi", "<cmd>Telescope lsp_implementations<CR>", opts)

					-- show lsp type definitions
					opts.desc = "Show LSP type definitions"
					vim.keymap.set("n", "gt", "<cmd>Telescope lsp_type_definitions<CR>", opts)

					-- see type hinting information
					opts.desc = "Show signature_help"
					vim.keymap.set("n", "<leader>gs", vim.lsp.buf.signature_help, opts)

					-- smart rename
					opts.desc = "Smart rename"
					vim.keymap.set("n", "<leader>rn", vim.lsp.buf.rename, opts)

					-- show  diagnostics for file
					opts.desc = "Show buffer diagnostics"
					vim.keymap.set("n", "<leader>D", "<cmd>Telescope diagnostics bufnr=0<CR>", opts)

					-- jump to previous diagnostic in buffer
					opts.desc = "Go to previous diagnostic"
					vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)

					-- jump to next diagnostic in buffer
					opts.desc = "Go to next diagnostic"
					vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)

					-- mapping to restart lsp if necessary
					opts.desc = "Restart LSP"
					vim.keymap.set("n", "<leader>rs", ":LspRestart<CR>", opts)
				end,
			},
			-- DAP configuration
			-- dap = {
			-- 	-- adapter = require("rust-tools.dap").get_codelldb_adapter(codelldb_path, liblldb_path),
			-- },
		}
	end,
}
```
nvim-cmp.lua

```lua
return {
  "hrsh7th/nvim-cmp",
  event = "InsertEnter",
  dependencies = {
    "hrsh7th/cmp-buffer",         -- source for text in buffer
    "hrsh7th/cmp-path",           -- source for file system paths
    "hrsh7th/cmp-cmdline",        -- source for cmdline
    "L3MON4D3/LuaSnip",           -- snippet engine
    "saadparwaiz1/cmp_luasnip",   -- for autocompletion
    "rafamadriz/friendly-snippets", -- useful snippets
    "onsails/lspkind.nvim",       -- vs-code like pictograms
  },
  config = function()
    local cmp = require("cmp")
    local luasnip = require("luasnip")
    local lspkind = require("lspkind")

    -- loads vscode style snippets from installed plugins (e.g. friendly-snippets)
    require("luasnip.loaders.from_vscode").lazy_load()

    cmp.setup({
      completion = {
        completeopt = "menu,menuone,preview,noselect",
      },
      window = {
        completion = cmp.config.window.bordered(),
        documentation = cmp.config.window.bordered(),
      },
      snippet = { -- configure how nvim-cmp interacts with snippet engine
        expand = function(args)
          luasnip.lsp_expand(args.body)
        end,
      },
      mapping = cmp.mapping.preset.insert({
        ["<C-j>"] = cmp.mapping.select_next_item(), --({ behavior = cmp.SelectBehavior, count = 1 }) next suggestion
        ["<C-k>"] = cmp.mapping.select_prev_item(), -- previous suggestion
        ["<C-d>"] = cmp.mapping.open_docs(-4),  -- open documentation for completion
        ["<C-b>"] = cmp.mapping.scroll_docs(-4),
        ["<C-f>"] = cmp.mapping.scroll_docs(4),
        -- ["<C-i>"] = cmp.mapping.complete(), -- show completion suggestions !!! this now fucks with tab and thats not on !!!
        ["<C-e>"] = cmp.mapping.abort(), -- close completion window
        ["<CR>"] = cmp.mapping.confirm({ select = true }),
      }),
      -- sources for autocompletion
      sources = cmp.config.sources({ -- order of the completions
        { name = "nvim_lsp" },    -- lsp sources
        { name = "luasnip" },     -- snippets
        { name = "buffer" },      -- text within current buffer
        { name = "path" },        -- file system paths
      }),
      -- configure lspkind for vs-code like pictograms in completion menu
      formatting = {
        format = lspkind.cmp_format({
          maxwidth = 60,
          ellipsis_char = "...",
        }),
      },
    })

    -- Use buffer source for `/` and `?` (if you enabled `native_menu`, this won't work anymore).
    cmp.setup.cmdline({ "/", "?" }, {
      mapping = cmp.mapping.preset.cmdline(),
      sources = {
        { name = "buffer" },
      },
    })

    -- Use cmdline & path source for ':' (if you enabled `native_menu`, this won't work anymore).
    cmp.setup.cmdline(":", {
      sources = cmp.config.sources({
        { name = "cmdline" },
      }, {
        { name = "path" },
      }),
      mapping = cmp.mapping.preset.cmdline({
        ["<C-k>"] = cmp.mapping.select_prev_item(), -- previous suggestion
        ["<C-j>"] = cmp.mapping.select_next_item(), -- next suggestion
      }),
    })
  end,
}
```
```

**Comment by mrcjkb** [comment]
Hey :wave: 

I use cmp-nvim-lsp, and rustaceanvim loads the capabilities without any issues.

Earlier today, I pushed a fix for a bug that was affecting Windows (#273). Perhaps this was affecting you and updating to the latest version of this plugin will resolve it for you.

If not, it could be a conflict with another plugin or setting, so you'd have to start from a minimal config without any other plugins - see the [troubleshooting/minimal config](https://github.com/mrcjkb/rustaceanvim?tab=readme-ov-file#minimal-config) section in the readme.

**Comment by Alan-Manning** [comment]
ok, so if i open with admin it started working. then i tried again in non-admin and it was working but then stopped working in admin. Now if i open in admin it works again but not in non-admin. It Flips flops between working in admin and working in non-admin. very very strange.

**Comment by mrcjkb** [comment]
> ok, so if i open with admin it started working. then i tried again in non-admin and it was working but then stopped working in admin. Now if i open in admin it works again but not in non-admin. It Flips flops between working in admin and working in non-admin. very very strange.

That sounds like you could be having issues with write permissions in your cache directories?
I don't know how that works in Windows though.

**Comment by Alan-Manning** [comment]
yeah i have done some permissions settings and stuff and seems to be working now so i will close issue. but yeah i also still don't know how that works in Windows though.
